### ISSUE TITLE
ES 6.1t 

### ISSUE THREAD

**Issue by gransy** [miku/esbulk#14]
After upgrade ES to 6.1, the esbulk works incorrectly for me. 

I start command with processes by count of cores, and with verbose i see how all processes doing bulk insert .. in few time a lot of processes ended without any error (i try put some logging) and thee is keep just one or two who fill finish insert. After last inserted data, the program is not finished and keep on this unknown state without any logging.

In total in ES is inserted total_docs-(10000*(processes-1)). In 24 processes i lost about 230.000 records.

**Comment by miku** [comment]
@gransy, if you overload the server by using too many workers, failures are expected - as the elasticsearch bulk API will return an error and this error let's esbulk stop the import process (see: [caveat](https://github.com/miku/esbulk#esbulk)).

Can you try to indexing with fewer workers? If it still fails, can you share a log - e.g. output with `-verbose` flag?

**Comment by gransy** [comment]
Hi, 

i use a command:

esbulk -server http://server:9200 -index logs-2018-02-04 -verbose 2018-02-04_.log.json >> esb.log 2> esb2.log

But command is no ever ending. I was kill it (Ctrl+C) after some hours.

The log is attached. As you see, each workers finish early during the process.

[esb2.log](https://github.com/miku/esbulk/files/1714227/esb2.log)

**Comment by miku** [comment]
@gransy, thanks for providing more details. 

> But command is no ever ending. 

That's unfortunate and something I haven't encountered yet. As a first measure, I will try to add more logging information to esbulk, so debugging might become easier.

As a sidenote: Please make sure, you are always using the newest version, at this moment, this would be [esbulk 0.4.9](https://github.com/miku/esbulk/releases/tag/v0.4.9).

**Comment by gransy** [comment]
Hi, 

finally my issue is not about your processing data, but about your handling errors. I found the problem in my cluster - one data node is not worked correctly. After correct my cluster, esbulk works again perfect. For this reasson i think, that there is something wrong in error detection. 

Jan

**Comment by miku** [comment]
@gransy, glad it worked out.
