### ISSUE TITLE
Provide docker image

### ISSUE THREAD

**Issue by albertpastrana** [miku/esbulk#25]
Hey @miku, first of all, thanks a lot for your project, it's great and it's been proving really helpful to us :).

We were thinking it would be great if `esbulk` could be package inside a docker image as an easy way of "installing" and distributing it.

We've created a repo with a simple Dockerfile:
https://github.com/intenthq/esbulk-docker

And we've automated the build and published it as well:
https://hub.docker.com/r/intenthq/esbulk-docker/

If you want to include this in your repo (either the Dockerfile) or just a link to docker hub feel free to do it or ask for any help :)

**Comment by miku** [comment]
> Hey @miku, first of all, thanks a lot for your project, it's great and it's been proving really helpful to us :).

Glad to hear that.

> And we've automated the build and published it as well

Wonderful. 

> If you want to include this in your repo (either the Dockerfile) or just a link to docker hub feel free to do it or ask for any help :)

I will update the README shortly and will dig a bit deeper into this.

Thanks a lot! - I'll keep this issue open for now to add updates on progress.

**Comment by miku** [comment]
For 0.5.2, I started to to include a [Dockerfile](https://github.com/miku/esbulk/blob/master/Dockerfile) in the repo. However, there is no official Dockerhub image yet.

**Comment by miku** [comment]
This should work now:

```
$ docker run -it --rm tirtir/esbulk -v
0.5.2
```

I would close this issue soon.
