### ISSUE TITLE
support OpType

### ISSUE THREAD

**Issue by gransy** [miku/esbulk#26]
Hi, 

please add support for Operation type: create / index - now you have fixed index (indexing.go:99).

With index - the data under same _id was replaced by new data
With create - the doc will not create if exists under same _id

(https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html)

Its perfect if you dont want duplicity and also dont want replace current data in ES.

Jan

**Comment by miku** [comment]
Thanks for the input.

> Its perfect if you dont want duplicity and also dont want replace current data in ES.

Sounds good.

Note to self: [indexing.go#L98](https://github.com/miku/esbulk/blob/e933f90e0abbdfacf27672732980aa6472e55ea8/indexing.go#L98)

**Comment by miku** [comment]
Done, via #38.
