### ISSUE TITLE
Is it possible to identify certain field as document id

### ISSUE THREAD

**Issue by RobGThai** [miku/esbulk#3]
I'm using Elasticsearch to store data from MySql. I wanted to keep row ID in MySql and ES's Document ID, identical. Is it possible to do so with ESBulk?

**Comment by miku** [comment]
Thanks for the report, it seems useful to allow reuse of IDs. I added support for it in [0.3.8](https://github.com/miku/esbulk/releases/tag/v0.3.8), via an command line flag, that allow the ID field to be specified. See [README for details](https://github.com/miku/esbulk#reusing-ids).

**Comment by RobGThai** [comment]
That's cool. Thanks. With this it will updating document with the same ID instead of adding it, right?

**Comment by miku** [comment]
Yes, exactly, it is standard ES behavior. Under the hood, if the `-id` flag is set to some value, esbulk will [peek](https://github.com/miku/esbulk/blob/5761fbe35b559a3553db58564b6e23789da6378d/common.go#L78) into the document at hand and will extract the value of the specified field and will use put it in the header for the bulk [indexing](https://www.elastic.co/guide/en/elasticsearch/guide/current/index-doc.html) as `_id`.

There is one, kind of, edge case: If the id field of your documents is actually named `_id` elasticsearch will complain. esbulk handles this by [automatically removing](https://github.com/miku/esbulk/blob/5761fbe35b559a3553db58564b6e23789da6378d/common.go#L92) the `_id` from the document - but this should be a rare case and even when this happens, it should do the right thing.

Let me know, if you encounter any bugs. If not then I would close this issue soon. Thanks!

**Comment by RobGThai** [comment]
I'm getting `json: cannot unmarshal number into Go value of type string`

This is probably my document id is store in number format inside json.

**Comment by miku** [comment]
Thanks for testing! I see the problem and hopefully fixed it with [v0.3.9](https://github.com/miku/esbulk/releases/tag/v0.3.9). Now string and numeric ids are [allowed](https://github.com/miku/esbulk/blob/201490f089028d2e5536f6014b50378d709c613f/common.go#L94).

**Comment by RobGThai** [comment]
Yes, it works fine now thanks a lot :)
