### ISSUE TITLE
Installing by "go install" not working because of replace in .mod

### ISSUE THREAD

**Issue by Jesibu** [miku/esbulk#40]
Hi,

I tried to install esbulk like documented in the readme: 

`go install github.com/miku/esbulk/cmd/esbulk@latest`

that is not anymore because of the replace directive in the .mod file that was added two month ago.

```
The go.mod file for the module providing named packages contains one or  
        more replace directives. It must not contain directives that would cause 
        it to be interpreted differently than if it were the main module.
```

Docker is not possible for me. Is there another way to install the Tool? (new to go and its environment ;) )

**Comment by miku** [comment]
Thanks for the report, I updated the docker dependency (which is only used at test time). It should work now.

**Comment by Jesibu** [comment]
That was the quickest response and fix I have ever seen :) Thanks mate
