### ISSUE TITLE
Authentication problem

### ISSUE THREAD

**Issue by andresKM** [miku/esbulk#6]
I secured my elastic (v5.0.1) with X-PACK and now it's not clear how to do the import...
Any thoughts?

**Comment by miku** [comment]
Thanks for the report. It seems X-Pack works with HTTP [basic auth](https://www.elastic.co/guide/en/x-pack/current/http-clients.html), so it should be no problem to add a flag for `-user`, similar to curl.

**Comment by miku** [comment]
@andresKM, I just published [0.4.2](https://github.com/miku/esbulk/releases/tag/v0.4.2), which has support for X-Pack. Just pass your username and password to the `-u` flag:

```
$ esbulk -u elastic:changeme -index abc file.ldj
```

**Comment by miku** [comment]
In case you encounter any more problems with the X-Pack support, please let me know. Thanks!
